### ISSUE TITLE
feat: Webex Teams support

### ISSUE THREAD

**Issue by jbpratt** [aws-samples/aws-health-organizational-view-alerts#1]
Developing a Lambda for Webex Teams chat service would be awesome and should be pretty straight forward. Extending this much more, it may be beneficial to abstract some of the code re-used across the lambdas into a layer, maybe even combining the template into a single template with a parameter to pick the service to deploy. Something like this, and conditions may work:
```
Parameters:
    Service:
        Type: String
        Default: Chime
        AllowedValues:
          - "Chime"
          - "MS Teams"
          - "Webex Teams"
          - "Slack"
```
